FUNC LABEL 0
    MOV REG 0 VAL 1
    MOV REG 1 VAL 0
    MOV REG 2 VAL 16
    MOV REG 3 VAL 100
    NOT REG 0
    NOT REG 1
    NOT REG 2
    NOT REG 3
    PRINT REG 0
    PRINT REG 1
    PRINT REG 2
    PRINT REG 3
    RET