FUNC LABEL 5
    PRINT VAL 1
    MOV STK A VAL 2
    PRINT STK A
    MOV STK A VAL 3
    REF STK B STK A
    PRINT PTR B
    MOV REG 0 VAL 4
    PRINT REG 0
    PRINT VAL 10
    PRINT VAL 100
    RET
