FUNC LABEL 0
    MOV STK A VAL 1
    PRINT STK A
    MOV REG 0 VAL 20
    MOV STK A REG 0
    PRINT STK A
    MOV STK B VAL 3
    MOV STK A STK B
    PRINT STK A
    REF STK B STK A
    MOV STK A PTR B
    PRINT STK A
    REF STK C STK A
    MOV PTR C VAL 2
    PRINT STK A
    MOV REG 0 VAL 20
    MOV PTR C REG 0
    PRINT STK A
    MOV REG 0 VAL 20
    MOV PTR C STK A
    PRINT STK A
    MOV STK B VAL 3
    REF STK A STK B
    REF STK C STK A
    MOV PTR C PTR A
    PRINT STK A
    MOV PTR C VAL 2
    PRINT STK A
    CAL VAL 1
    RET
FUNC LABEL 1
    MOV REG 0 VAL 3
    MOV REG 1 VAL 4
    MOV REG 2 VAL 5
    MOV REG 3 VAL 6
    PRINT REG 0
    PRINT REG 1
    PRINT REG 2
    PRINT REG 3
    RET